### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by dndnp4** [kr-MATAGI/De-identification-NER-Datasets#1]
갤럭시워치4 2마논에 삽니다

**Comment by kr-MATAGI** [comment]
p{margin-top:0;margin-bottom:0}
    


    니 맘대로 이슈 쓰지마라 ㅋㅋㅋㅋㅋㅋㅋ
--------- 원본 메일 ---------

    
        보낸사람: 밋꾸 ***@***.***>
        받는사람: kr-MATAGI/De-identification-NER-Datasets ***@***.***>
        
            참조: Subscribed ***@***.***>
        
        날짜: 22.04.13 10:49 GMT +0900
        제목: [kr-MATAGI/De-identification-NER-Datasets] 안녕하세요 (Issue #1)
        
        
    
    
        

갤럭시워치4 2마논에 삽니다

**Comment by kr-MATAGI** [comment]
기각
